USE [master]
GO
/****** Object:  Database [JobbrDemo]    Script Date: 06.03.2015 20:17:44 ******/
CREATE DATABASE [JobbrDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JobbrDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\JobbrDemo.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'JobbrDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\JobbrDemo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [JobbrDemo] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JobbrDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JobbrDemo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JobbrDemo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JobbrDemo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JobbrDemo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JobbrDemo] SET ARITHABORT OFF 
GO
ALTER DATABASE [JobbrDemo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JobbrDemo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JobbrDemo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JobbrDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JobbrDemo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JobbrDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JobbrDemo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JobbrDemo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JobbrDemo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JobbrDemo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [JobbrDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JobbrDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JobbrDemo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JobbrDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JobbrDemo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JobbrDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JobbrDemo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JobbrDemo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JobbrDemo] SET  MULTI_USER 
GO
ALTER DATABASE [JobbrDemo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JobbrDemo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JobbrDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JobbrDemo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [JobbrDemo] SET DELAYED_DURABILITY = DISABLED 
GO
USE [JobbrDemo]
GO
/****** Object:  Schema [Jobbr]    Script Date: 06.03.2015 20:17:44 ******/
CREATE SCHEMA [Jobbr]
GO
/****** Object:  Table [Jobbr].[JobRuns]    Script Date: 06.03.2015 20:17:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Jobbr].[JobRuns](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[JobId] [bigint] NOT NULL,
	[TriggerId] [bigint] NOT NULL,
	[UniqueId] [char](36) NOT NULL,
	[JobParameters] [varchar](max) NULL,
	[InstanceParameters] [varchar](max) NULL,
	[PlannedStartDateTimeUtc] [datetime2](7) NOT NULL,
	[ActualStartDateTimeUtc] [datetime2](7) NULL,
	[EstimatedEndDateTimeUtc] [datetime2](7) NULL,
	[ActualEndDateTimeUtc] [nchar](10) NULL,
	[Progress] [int] NULL,
	[State] [varchar](15) NOT NULL,
	[Pid] [int] NULL,
	[WorkingDir] [varchar](300) NULL,
	[TempDir] [varchar](300) NULL,
 CONSTRAINT [PK_JobRuns] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [Jobbr].[Jobs]    Script Date: 06.03.2015 20:17:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Jobbr].[Jobs](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Type] [varchar](50) NOT NULL,
	[CreatedDateTimeUtc] [datetime2](7) NOT NULL,
	[UpdatedDateTimeUtc] [datetime2](7) NULL,
 CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [Jobbr].[Triggers]    Script Date: 06.03.2015 20:17:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Jobbr].[Triggers](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[JobId] [bigint] NOT NULL,
	[TriggerType] [varchar](10) NOT NULL,
	[Definition] [varchar](20) NULL,
	[StartDateTimeUtc] [datetime2](7) NULL,
	[DelayedInMinutes] [int] NULL,
	[IsActive] [bit] NOT NULL,
	[UserId] [bigint] NULL,
	[UserName] [nvarchar](50) NULL,
	[UserDisplayName] [varchar](100) NULL,
	[Parameters] [varchar](max) NULL,
	[Comment] [varchar](max) NULL,
 CONSTRAINT [PK_Triggers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [JobbrDemo] SET  READ_WRITE 
GO
